### ISSUE TITLE
[tutorial] Services classes and plans have changed

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/k8s-service-catalog#208]
Tutorial references:
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: gcp-pubsub-instance
  namespace: gcp-pubsub-app
spec:
  clusterServiceClassExternalName: pubsub
  clusterServicePlanExternalName: pubsub-plan
```

But:

```
kubectl get clusterserviceclass \
--output='custom-columns=BROKER:.spec.clusterServiceBrokerName,EXTERNAL NAME:.spec.externalName'
BROKER       EXTERNAL NAME
gcp-broker   cloud-spanner
gcp-broker   cloud-iam-service-account
gcp-broker   cloud-pubsub
gcp-broker   cloud-sql-mysql
gcp-broker   bigquery
gcp-broker   cloud-bigtable
gcp-broker   cloud-storage

kubectl get clusterserviceplan \
--output='custom-columns=BROKER:.spec.clusterServiceBrokerName,EXTERNAL NAME:.spec.externalName'
BROKER       EXTERNAL NAME
gcp-broker   beta
gcp-broker   beta
gcp-broker   beta
gcp-broker   beta
gcp-broker   beta
gcp-broker   beta
gcp-broker   beta
```
The lists have expanded and this should be reflected.

More importantly, the externalNames are both changed:

```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: gcp-pubsub-instance
  namespace: gcp-pubsub-app
spec:
  clusterServiceClassExternalName: cloud-pubsub
  clusterServicePlanExternalName: beta
```
